  services:
    - type: web
      name: swinka-cv
      env: ruby
      region: frankfurt     # najbliżej PL
      plan: free            # możesz zmienić na starter, gdy będziesz potrzebował
      buildCommand: |
        bundle install
        yarn install
        bundle exec rake assets:precompile
      startCommand: bundle exec puma -C config/puma.rb
      envVars:
        - key: RAILS_MASTER_KEY
          sync: false
        - key: OPENAI_API_KEY
          sync: false
        - key: OPENAI_MODEL
          value: gpt-4.1    # lub Twój domyślny model
      autoDeploy: true
      healthCheckPath: /

  databases:
    - name: swinka-cv-db
      region: frankfurt
      plan: free

 
